[project]
name = "thunderstore"
version = "0.3.0"
description = "thunderstore.io modpage support for Mod Organizer 2"
authors = [{ name = "Zash", email = "zash@fantasymail.de" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = []

[project.scripts]
thunderstore-protocol = "thunderstore.protocol.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.32.4.20250913"
ruff = "^0.13.0"
poethepoet = "^0.37.0"
mypy = "^1.18.1"
pyright = "^1.1.405"
mobase-stubs = "^2.5.2"
pyqt6 = "^6.7.0"

[tool.poetry.group.build.dependencies]
nuitka = "^2.8.1"

[tool.poetry.group.build]
optional = true

[tool.poe.tasks]
format-imports = "ruff check --select I . --fix"
format-ruff = "ruff format ."
format.sequence = ["format-imports", "format-ruff"]
lint-ruff = "ruff check --extend-select I ."
lint-ruff-format = "ruff format --check ."
lint-pyright = "pyright ."
lint-mypy = "mypy . --exclude-gitignore"
lint.sequence = ["lint-ruff", "lint-ruff-format", "lint-pyright", "lint-mypy"]
lint.ignore_fail = "return_non_zero"

[tool.poe.tasks.build]
help = "small thunderstore/protocol/thunderstore_protocol_handler_*.exe, requires matching Python version under MO/plugins/plugin_python/dlls"
shell = """python -m nuitka thunderstore/protocol \
    --mode=accelerated \
    --windows-console-mode=hide \
    --no-deployment-flag=self-execution \
    --output-dir=build \
    --output-filename=thunderstore/protocol/thunderstore_protocol_handler_${PYTHON_VERSION}.exe"""
uses = { PYTHON_VERSION = "_python-version"}

[tool.poe.tasks._python-version]
expr="'python{}{}'.format(*sys.version_info[:2])"

[tool.poe.tasks.build-standalone]
help = "MO independent exe, bundled with Python"
shell = """python -m nuitka thunderstore/protocol \
    --mode=onefile \
    --windows-console-mode=hide \
    --no-deployment-flag=self-execution \
    --output-dir=build \
    --output-filename=thunderstore_protocol_handler.exe \
    && mv -t thunderstore/protocol/ build/thunderstore_protocol_handler.exe"""
    # Workaround for filename path [bug](https://github.com/Nuitka/Nuitka/issues/3642)

[tool.poe.tasks.pack]
help = "Pack the plugin, including compiled exe"
shell = "./pack-release.sh $ref $output"
args.output = {options = ["-o", "--output"], help="[default: thunderstore-$(poetry version -s).zip]"}
args.ref = {default="HEAD", positional=true}

[tool.poe.tasks.update-version]
cmd = "python update_version.py -s ${version}"
args.version = {positional=true, help="See: poetry version --help"}
help = "Update project and plugin version"

[tool.pyright]
reportMissingModuleSource = false
